// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1EnpNnqnkUaCze-kJdU2OT-fzu-wUiZs',
    appId: '1:215131575332:web:effa5b01b5d3b456acb4b1',
    messagingSenderId: '215131575332',
    projectId: 'feedback-auth-app',
    authDomain: 'feedback-auth-app.firebaseapp.com',
    storageBucket: 'feedback-auth-app.appspot.com',
    measurementId: 'G-VZ351E89WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ8ZRrVqASXr6BfYW4RaV6FAaOQ5P1fBg',
    appId: '1:215131575332:android:dc98f2abb742f14aacb4b1',
    messagingSenderId: '215131575332',
    projectId: 'feedback-auth-app',
    storageBucket: 'feedback-auth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBECrpubCcf149U92g5jCQgK-XV8qVriSg',
    appId: '1:215131575332:ios:7b1253235fb19782acb4b1',
    messagingSenderId: '215131575332',
    projectId: 'feedback-auth-app',
    storageBucket: 'feedback-auth-app.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBECrpubCcf149U92g5jCQgK-XV8qVriSg',
    appId: '1:215131575332:ios:106eafdfbeb56a7dacb4b1',
    messagingSenderId: '215131575332',
    projectId: 'feedback-auth-app',
    storageBucket: 'feedback-auth-app.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
